from django.db import models

# Create your models here.
class Respondent(models.Model):
    # primary key will be autogenerated
    age = models.CharField(max_length=50, default="None") # since age is a range
    gender = models.CharField(max_length=50, default="None")
    education = models.CharField(max_length=50, default="None")
    ip_addr = models.CharField(max_length=50, default="0.0.0.0")
    
    def __str__(self):
        return self.age + ", " + self.gender + ", " + self.education
    
class Algorithm(models.Model):
    name = models.CharField(max_length=10)
    
    def __str__(self):
        return self.name

class Query(models.Model):
    # the name of the query (i.e. 'women's world cup')
    query_name = models.CharField(max_length=100)
    # this id of the query in the txt files
    # there is no query with id 0
    query_id = models.PositiveSmallIntegerField(default=0)
    def __str__(self):
        return self.query_name
    
class Response(models.Model):
    respondent_id = models.IntegerField()
    query_id = models.IntegerField()
    chosen_alg_id = models.IntegerField()
    unchosen_alg_id = models.IntegerField()
    # if we want to store more accurate time data, change this
    time_elapsed = models.PositiveSmallIntegerField()
    
    def __str__(self):
        return "Query: " + Query.objects.filter(query_id=self.query_id)[0].query_name
    
    

    