# Generated by Django 2.2.6 on 2019-10-25 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Algorithm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Respondent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_elapsed', models.PositiveSmallIntegerField()),
                ('chosen_alg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chosen', to='version2.Algorithm')),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='version2.Query')),
                ('respondent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='version2.Respondent')),
                ('unchosen_alg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unchosen', to='version2.Algorithm')),
            ],
        ),
    ]
