# Generated by Django 2.2.6 on 2019-11-13 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Algorithm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_name', models.CharField(max_length=100)),
                ('query_id', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Respondent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(default='None', max_length=50)),
                ('gender', models.CharField(default='None', max_length=50)),
                ('education', models.CharField(default='None', max_length=50)),
                ('ip_addr', models.CharField(default='0.0.0.0', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respondent_id', models.IntegerField()),
                ('query_id', models.IntegerField()),
                ('chosen_alg_id', models.IntegerField()),
                ('unchosen_alg_id', models.IntegerField()),
                ('time_elapsed', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
