# Generated by Django 2.2.6 on 2019-10-25 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('version2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='query_id',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
