# Generated by Django 2.2.6 on 2019-10-26 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('version2', '0002_query_query_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='respondent',
            name='education',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='respondent',
            name='gender',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
