# Generated by Django 2.2.6 on 2019-11-13 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('version2', '0004_auto_20191027_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='respondent',
            name='ip_addr',
            field=models.CharField(default='0.0.0.0', max_length=50),
        ),
    ]
