# Generated by Django 2.2.6 on 2019-11-13 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('version2', '0004_auto_20191027_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='respondent',
            name='ip_address',
            field=models.GenericIPAddressField(default=0),
        ),
    ]
