# Generated by Django 2.2.6 on 2019-11-13 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('version2', '0005_respondent_ip_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respondent',
            name='ip_address',
        ),
        migrations.AddField(
            model_name='respondent',
            name='ip_addr',
            field=models.CharField(default='0.0.0.0', max_length=50),
        ),
    ]
